info:
  app.name: "${jar.baseName}"
  app.description: "${description}"
  app.version: "${version}"

spring:
  application:
    name: techtalk-springcloud-config
  cloud:
    config:
      server:
        git:
          uri: file:///srv/System73/Projects/techtalk-springcloud-config

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8002/eureka/
  instance:
    status-page-url-path: /manage/info
    health-check-url-path: /manage/health
    metadata-map:
      management.context-path: /manage

management:
  context-path: /manage
  security:
    enabled: false

server:
  port: 8001
