info:
  app.name: "${jar.baseName}"
  app.description: "${description}"
  app.version: "${version}"

eureka:
  client:
    healthcheck:
      enabled: true

management:
  context-path: /manage
  security:
    enabled: false


server:
  port: 8003
