spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

tech-talk:
  graphite:
    host: localhost
    port: 2003
  message: Mensaje de texto :P
