info:
  app.name: "${jar.baseName}"
  app.description: "${description}"
  app.version: "${version}"

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization-inclusion: NON_NULL
    serialization:
      WRITE_EMPTY_JSON_ARRAYS: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

eureka:
  client:
    healthcheck:
      enabled: true

management:
  context-path: /manage
  security:
    enabled: false

server:
  port: 8000
